### ISSUE TITLE
[BUG]: Issue when artist don't have an album

### ISSUE THREAD

**Issue by pierricktly** [zS1L3NT/ts-npm-ytmusic-api#10] opened 2022-12-28 13:20 UTC
### Please describe the current behaviour of the code.

I have noticed that when attempting to do a get on an artist who does not have an album, it does not work due to the fact that contents returns undefined.

### Please describe the expected behaviour of the code.

I'm guessing that when the artist does not have any albums, it would be appropriate to return an empty list?

### What are the steps to reproduce the error?

Get an artist without an album, I tried with this [YTM](https://music.youtube.com/channel/UCguLk541HUGblR0kPvbnX_Q)

**Comment by zS1L3NT** [comment] 2022-12-29 02:21
Version v4.0.2 has been released with the fix included

**Comment by Zokiasu** [comment] 2022-12-29 08:52
Hi! Thank you for the fix, however I'm not sure if the problem is with YouTube Music or how the data is being retrieved. When an artist only has singles, they are considered in the topAlbums list and the top videos are in the topSingles list etc...

I tried with this two UCDDpqmryjNunitS05bv7-8w and UCAl7xQ6q0PEgZMQD7zr4AKQ

**Comment by Zokiasu** [comment] 2023-02-05 21:16
Hi! No idea how to fix this issue?

**Comment by zS1L3NT** [comment] 2024-01-12 15:08
Is the v5.x working better regarding missing values?

**Closed** 2024-01-14 09:46 UTC
Labels: bug
