### ISSUE TITLE
[BUG]: YTMusic is not a constructor

### ISSUE THREAD

**Issue by SomeAspy** [zS1L3NT/ts-npm-ytmusic-api#30] opened 2024-03-18 03:03 UTC
### Please describe the current behaviour of the code.

Following the example in the readme will cause a `TypeError: YTMusic is not a constructor`

### Please describe the expected behaviour of the code.

This error should not occur

### What are the steps to reproduce the error?

Slightly modified code based off the readme example:
```ts
import YTMusic from "ytmusic-api";

import untypedConfig from "../config/config.json" assert { type: "json" };
import type { Config } from "./types/config.js";
const { YouTubeMusicCookie } = untypedConfig as Config;

const YTM = new YTMusic(); // "TypeError: YTMusic is not a constructor" on build

await YTM.initialize({cookies:YouTubeMusicCookie})

await YTM.getArtist("Dirt Poor Robins").then(results=>{
    console.log(results)
});
```

### Additional Information

typescript 5.4.2 (also tested with 5.2.2)
tsx 4.7.1
ytmusic-api 5.2.1
node 21.7.1 (also tested with 18.19.1)

**Comment by zS1L3NT** [comment] 2024-03-18 03:38
How has this issue not surfaced earlier? Did it break with the newer versions of TypeScript?

**Comment by SomeAspy** [comment] 2024-03-18 04:36
I am unsure, this is my first time working with this package. I also found a near identical issue on another Youtube Music API package (https://github.com/nickp10/youtube-music-ts-api/issues/33) There is a possibility this could be on me if you are unable to reproduce. I can send my `tsconfig.json` too if it might help

**Comment by tomwallyn** [comment] 2024-03-25 09:37
I had the same problem. You can use the **.default** method which resolved the issue for me.

`import YTMusic from 'ytmusic-api'

export default class YtbMusicService {
  private ytmusic: any

  constructor() {
    this.ytmusic = new YTMusic.default()
  }

  async searchMusics(query: string) {
    try {
      await this.ytmusic.initialize()
      const searchResults = await this.ytmusic.search(query)
      return searchResults
    } catch (error) {
      throw new Error(`Failed to search for musics: ${error}`);
    }
  }
}
`

**Comment by omathdevelop** [comment] 2024-04-09 23:31
Still not working,  what is the essence of keeping this project alive when nothing works and the author could not fix the bug???

**Comment by omathdevelop** [comment] 2024-04-09 23:33
anyone here know a very good alternative pkg??

**Comment by SomeAspy** [comment] 2024-04-10 21:09
> Still not working, what is the essence of keeping this project alive when nothing works and the author could not fix the bug???

While I understand the frustration behind finding a package you need to use seemingly unmaintained, we shouldn't berate the developer, as they are unpaid and do this in their free time.

**Comment by zS1L3NT** [comment] 2024-04-11 04:35
Apologies for the late responses. Thanks @SomeAspy for the understanding.

I can't find a good way to reproduce this? I created a new node project and installed ytmusic-api into it and it worked fine...

**Comment by raed667** [comment] 2024-04-11 07:03
I managed to reproduce the issue using codesandbox : https://codesandbox.io/p/devbox/agitated-sun-s2572k?file=%2Findex.mjs%3A4%2C38

**Comment by SomeAspy** [comment] 2024-04-11 23:01
> I managed to reproduce the issue using codesandbox : [codesandbox.io/p/devbox/agitated-sun-s2572k?file=%2Findex.mjs%3A4%2C38](https://codesandbox.io/p/devbox/agitated-sun-s2572k?file=%2Findex.mjs%3A4%2C38)

This link appears to be a 404

**Comment by raed667** [comment] 2024-04-12 07:39
apologies it was set as private by default. Should have access now.

**Comment by femke77** [comment] 2024-04-13 00:33
nope still no access

**Comment by zS1L3NT** [comment] 2024-04-13 05:34
This package currently only supports CJS importing, so importing it as a module in JavaScript wont work... I'll work on the ESM module once I figure it out because I've never done much work regarding ESM so in the meantime try to import it with the `require()` statement

**Comment by Dajust** [comment] 2024-05-22 02:37
Still no progress...

**Comment by Dajust** [comment] 2024-05-22 03:29
Thanks, @tomwallyn, that actually works!

```mjs
import YTMusic from 'ytmusic-api';

const ytm: YTMusic = new YTMusic.default();
await ytm.initialize();
```

I guess the problem is in how the package does exports. Something isn't quite right.

**Comment by zS1L3NT** [comment] 2024-07-07 21:09
Version v5.2.2 has been released with this bug fixed. Apologies for the very late fix and reply

**Closed by zS1L3NT** 2024-07-07 21:09 UTC
Labels: bug
